name: Format Code using Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  pint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Composer dependancies
        run: composer install

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[pint] Apply Laravel Pint code-style fixes"
